//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace AydoganFBank.Database
{
    using System;
    using System.Collections.Generic;
    
    public partial class Account
    {
        public int AccountId { get; set; }
        public int OwnerId { get; set; }
        public int OwnerType { get; set; }
        public string AccountNumber { get; set; }
        public int AccountTypeId { get; set; }
        public decimal Balance { get; set; }
    }
}
