//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace AydoganFBank.Database
{
    using System;
    using System.Collections.Generic;
    
    public partial class AccountTransaction
    {
        public int TransactionId { get; set; }
        public int FromAccountId { get; set; }
        public int ToAccountId { get; set; }
        public decimal Amount { get; set; }
        public System.DateTime TransactionDate { get; set; }
        public int TransactionTypeId { get; set; }
        public int TransactionStatusId { get; set; }
        public Nullable<int> OwnerId { get; set; }
        public Nullable<int> OwnerType { get; set; }
        public Nullable<int> FromOwnerType { get; set; }
        public Nullable<int> FromOwnerId { get; set; }
        public Nullable<int> ToOwnerType { get; set; }
        public Nullable<int> ToOwnerId { get; set; }
    
        public virtual Account FromAccount { get; set; }
        public virtual Account ToAccount { get; set; }
        public virtual TransactionStatus TransactionStatus { get; set; }
        public virtual TransactionType TransactionType { get; set; }
    }
}
