//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace AydoganFBank.Database
{
    using System;
    using System.Collections.Generic;
    
    public partial class Application
    {
        public int ApplicationId { get; set; }
        public string Name { get; set; }
        public string Domain { get; set; }
        public string Token { get; set; }
        public System.Guid Guid { get; set; }
        public int TokenValidationMinute { get; set; }
        public int TokenSlidingMinute { get; set; }
        public int TokenSlidingCheckMinute { get; set; }
    }
}
