//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace AydoganFBank.Database
{
    using System;
    using System.Collections.Generic;
    
    public partial class CreditCardExtre
    {
        public int CreditCardExtreId { get; set; }
        public int CreditCardId { get; set; }
        public int Month { get; set; }
        public string MonthName { get; set; }
        public int Year { get; set; }
        public decimal TotalPayment { get; set; }
        public decimal MinPayment { get; set; }
        public bool IsDischarged { get; set; }
    }
}
