//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace AydoganFBank.Database
{
    using System;
    using System.Collections.Generic;
    
    public partial class CreditCard
    {
        public int CreditCardId { get; set; }
        public string CreditCardNumber { get; set; }
        public decimal Limit { get; set; }
        public decimal Debt { get; set; }
        public int ExtreDay { get; set; }
        public int Type { get; set; }
        public string ValidMonth { get; set; }
        public string ValidYear { get; set; }
        public string SecurityCode { get; set; }
        public bool IsInternetUsageOpen { get; set; }
        public int OwnerType { get; set; }
        public int OwnerId { get; set; }
    }
}
